use std::fs;
use std::path::{Path, PathBuf};

use crate::ir::load_ir;
use crate::metadata::{write_metadata, MetadataInput};
use crate::runtime::executions_for;

fn safe_identifier(text: &str) -> String {
    let mut out = String::new();
    let mut last_underscore = true;
    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_underscore = false;
        } else if !last_underscore {
            out.push('_');
            last_underscore = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        out.push_str("scenario");
    }
    out
}

pub struct GenerateOptions<'a> {
    pub ir_path: &'a Path,
    pub output_dir: &'a Path,
    pub feature_path: Option<&'a str>,
    pub handlers_crate: &'a str,
}

pub fn generate(opts: GenerateOptions<'_>) -> Result<Vec<PathBuf>, String> {
    let feature = load_ir(opts.ir_path)?;
    let feature_path = opts
        .feature_path
        .map(|s| s.to_string())
        .unwrap_or_else(|| opts.ir_path.to_string_lossy().to_string());
    let stem = Path::new(&feature_path)
        .file_stem()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "feature".to_string());
    fs::create_dir_all(opts.output_dir).map_err(|e| e.to_string())?;
    let test_file = opts.output_dir.join(format!(
        "{}_acceptance.rs",
        safe_identifier(&stem)
    ));

    let mut body = String::new();
    body.push_str("// Generated by acceptance-entrypoint-generator. Do not edit.\n");
    body.push_str(&format!("// Feature: {}\n", feature.name));
    body.push_str(&format!("// Source: {}\n", feature_path));
    body.push_str("use std::sync::Once;\n\n");
    body.push_str("use aps_kit::run_execution;\n");
    body.push_str(&format!(
        "use {}::register as register_handlers;\n\n",
        opts.handlers_crate
    ));
    body.push_str("static INIT: Once = Once::new();\n\n");
    body.push_str("fn ensure_registered() {\n    INIT.call_once(|| { register_handlers(); });\n}\n\n");
    body.push_str("fn ir_path() -> String {\n");
    body.push_str(
        "    std::env::var(\"APS_IR_PATH\").unwrap_or_else(|_| String::from(\""
    );
    body.push_str(&opts.ir_path.to_string_lossy());
    body.push_str("\"))\n}\n\n");

    for (s_idx, e_idx) in executions_for(&feature) {
        let scenario_name = safe_identifier(&feature.scenarios[s_idx].name);
        let fn_name = format!(
            "scenario_{:02}_{}_example_{:02}",
            s_idx,
            scenario_name,
            e_idx + 1
        );
        body.push_str("#[test]\n");
        body.push_str(&format!("fn {fn_name}() {{\n"));
        body.push_str("    ensure_registered();\n");
        body.push_str(&format!(
            "    run_execution(&ir_path(), {s_idx}, {e_idx}, None).expect(\"acceptance failure\");\n"
        ));
        body.push_str("}\n\n");
    }

    fs::write(&test_file, body).map_err(|e| e.to_string())?;

    let generated = vec![test_file.clone()];
    write_metadata(MetadataInput {
        metadata_dir: &opts.output_dir.join("metadata"),
        feature_path: &feature_path,
        ir_path: &opts.ir_path.to_string_lossy(),
        generated_files: &generated,
    })?;
    Ok(generated)
}
