// Acceptance entrypoint generator. Emits a vitest module for one feature.
import { mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

import { loadIR } from "./ir.js";
import { metadataFilename, writeMetadata } from "./metadata.js";
import { executionsFor } from "./runtime.js";

function safeIdentifier(text: string): string {
  const cleaned = text.replace(/[^A-Za-z0-9_]+/g, "_").replace(/^_+|_+$/g, "").toLowerCase();
  return cleaned || "scenario";
}

function moduleStem(featurePath: string): string {
  const stem = basename(featurePath).replace(/\.feature$/i, "");
  return `${safeIdentifier(stem)}.acceptance.test`;
}

export interface GenerateOptions {
  irPath: string;
  outputDir: string;
  featurePath?: string;
}

export function generate(opts: GenerateOptions): string[] {
  const feature = loadIR(opts.irPath);
  const featurePath = opts.featurePath ?? opts.irPath;
  const stem = moduleStem(featurePath);
  mkdirSync(opts.outputDir, { recursive: true });
  const testFile = join(opts.outputDir, `${stem}.ts`);

  const lines: string[] = [];
  lines.push("// Generated by acceptance-entrypoint-generator. Do not edit.");
  lines.push(`// Feature: ${feature.name}`);
  lines.push(`// Source: ${featurePath}`);
  lines.push(`import { test } from "vitest";`);
  lines.push(`import { runExecution } from "@aps-kit/typescript";`);
  lines.push("");
  lines.push(
    `const IR_PATH = process.env.APS_IR_PATH ?? ${JSON.stringify(opts.irPath)};`,
  );
  lines.push("");
  for (const [sIdx, eIdx] of executionsFor(feature)) {
    const scenarioName = safeIdentifier(feature.scenarios[sIdx].name);
    const testName = `scenario_${String(sIdx).padStart(2, "0")}_${scenarioName}_example_${String(eIdx + 1).padStart(2, "0")}`;
    lines.push(
      `test(${JSON.stringify(testName)}, () => {\n  runExecution(IR_PATH, ${sIdx}, ${eIdx});\n});`,
    );
    lines.push("");
  }

  writeFileSync(testFile, lines.join("\n").trimEnd() + "\n", "utf-8");

  const metadataDir = join(opts.outputDir, "metadata");
  const metadataPath = join(metadataDir, metadataFilename(featurePath));
  writeMetadata({
    metadataPath,
    featurePath,
    irPath: opts.irPath,
    generatedFiles: [testFile],
  });
  return [testFile];
}
