import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "vitest";

import { generate } from "../src/generator.js";

let dir: string;
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "aps-kit-"));
});
afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

function writeIR(payload: unknown): string {
  const path = join(dir, "ir.json");
  writeFileSync(path, JSON.stringify(payload));
  return path;
}

describe("generate", () => {
  test("emits one test per (scenario, example)", () => {
    const ir = writeIR({
      name: "F",
      scenarios: [
        {
          name: "with examples",
          steps: [{ keyword: "Then", text: "ok" }],
          examples: [{ a: "1" }, { a: "2" }],
        },
        {
          name: "no examples",
          steps: [{ keyword: "Then", text: "ok" }],
          examples: [],
        },
      ],
    });
    const out = join(dir, "out");
    const generated = generate({
      irPath: ir,
      outputDir: out,
      featurePath: "features/foo.feature",
    });
    expect(generated).toHaveLength(1);
    const body = readFileSync(generated[0], "utf-8");
    expect(body).toContain("Generated by acceptance-entrypoint-generator");
    const count = (body.match(/test\(/g) ?? []).length;
    expect(count).toBe(3);
    const meta = JSON.parse(
      readFileSync(join(out, "metadata", "features-foo-feature.json"), "utf-8"),
    );
    expect(meta.schema_version).toBe(1);
    expect(meta.implementation_hash.startsWith("sha256:")).toBe(true);
  });

  test("falls back to ir path when featurePath unspecified", () => {
    const ir = writeIR({
      name: "F",
      scenarios: [{ name: "s", steps: [{ keyword: "Then", text: "ok" }], examples: [] }],
    });
    const out = join(dir, "out");
    generate({ irPath: ir, outputDir: out });
    const metadataFiles = readdirSync(join(out, "metadata"));
    expect(metadataFiles).toHaveLength(1);
  });

  test("scenario with all-punctuation name falls back to default identifier", () => {
    const ir = writeIR({
      name: "F",
      scenarios: [
        {
          name: "@@@",
          steps: [{ keyword: "Then", text: "ok" }],
          examples: [],
        },
      ],
    });
    const out = join(dir, "out");
    const generated = generate({
      irPath: ir,
      outputDir: out,
      featurePath: "features/f.feature",
    });
    expect(readFileSync(generated[0], "utf-8")).toContain(
      "scenario_00_scenario_example_01",
    );
  });

  test("is deterministic for a fixed IR", () => {
    const ir = writeIR({
      name: "F",
      scenarios: [
        {
          name: "ordered",
          steps: [{ keyword: "Then", text: "ok" }],
          examples: [{ a: "1" }],
        },
      ],
    });
    const a = generate({
      irPath: ir,
      outputDir: join(dir, "a"),
      featurePath: "features/f.feature",
    });
    const b = generate({
      irPath: ir,
      outputDir: join(dir, "b"),
      featurePath: "features/f.feature",
    });
    expect(readFileSync(a[0], "utf-8")).toBe(readFileSync(b[0], "utf-8"));
  });
});
