package apskit

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFeatureIR(t *testing.T, dir string, feature Feature) string {
	t.Helper()
	data, _ := json.Marshal(feature)
	path := filepath.Join(dir, "ir.json")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestSafeIdentifierFallback(t *testing.T) {
	if SafeIdentifier("@@@") != "Scenario" {
		t.Errorf("expected fallback identifier")
	}
	if SafeIdentifier("Add Order") != "Add_Order" {
		t.Errorf("expected Add_Order, got %q", SafeIdentifier("Add Order"))
	}
}

func TestGenerateEmitsOneTestPerExecution(t *testing.T) {
	dir := t.TempDir()
	feature := Feature{
		Name: "F",
		Scenarios: []Scenario{
			{Name: "with examples", Steps: []Step{{Keyword: "Then", Text: "ok"}}, Examples: []map[string]string{{"a": "1"}, {"a": "2"}}},
			{Name: "no examples", Steps: []Step{{Keyword: "Then", Text: "ok"}}},
		},
	}
	ir := writeFeatureIR(t, dir, feature)
	outDir := filepath.Join(dir, "out")
	generated, err := Generate(GenerateOptions{
		IRPath:      ir,
		OutputDir:   outDir,
		FeaturePath: "features/foo.feature",
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(generated) != 1 {
		t.Fatalf("expected one generated file, got %d", len(generated))
	}
	body, _ := os.ReadFile(generated[0])
	count := strings.Count(string(body), "func Test_Scenario_")
	if count != 3 {
		t.Errorf("expected 3 test functions, got %d", count)
	}
	if !strings.Contains(string(body), "Generated by acceptance-entrypoint-generator") {
		t.Error("generated file missing canonical generator comment")
	}
	// Regression (mutate4go): the example index in the function name is
	// one-based (eIdx + 1). Pin exact names so mutations to the +1 offset
	// surface immediately.
	for _, want := range []string{
		"Test_Scenario_00_with_examples_Example_01",
		"Test_Scenario_00_with_examples_Example_02",
		"Test_Scenario_01_no_examples_Example_01",
	} {
		if !strings.Contains(string(body), "func "+want+"(") {
			t.Errorf("generated body missing function %q", want)
		}
	}
	// Regression (mutate4go): the metadata filename is derived from
	// FeaturePath. If the `if FeaturePath == ""` fallback fires when
	// FeaturePath is provided (the mutation flips == to !=), the filename
	// would derive from IRPath instead. Pin the expected filename.
	wantMeta := filepath.Join(outDir, "metadata", "features-foo-feature.json")
	if _, err := os.Stat(wantMeta); err != nil {
		t.Errorf("metadata not at %q: %v", wantMeta, err)
	}
}

func TestGenerateDefaultsFeaturePathAndPackage(t *testing.T) {
	dir := t.TempDir()
	feature := Feature{Name: "F", Scenarios: []Scenario{{Name: "s", Steps: []Step{{Keyword: "Then", Text: "ok"}}}}}
	ir := writeFeatureIR(t, dir, feature)
	outDir := filepath.Join(dir, "out")
	if _, err := Generate(GenerateOptions{IRPath: ir, OutputDir: outDir}); err != nil {
		t.Fatal(err)
	}
	// Default package name is "generated".
	files, _ := os.ReadDir(outDir)
	var found bool
	for _, f := range files {
		if strings.HasSuffix(f.Name(), "_acceptance_test.go") {
			body, _ := os.ReadFile(filepath.Join(outDir, f.Name()))
			if !strings.Contains(string(body), "package generated") {
				t.Errorf("expected default package, got %s", body)
			}
			found = true
		}
	}
	if !found {
		t.Error("no generated test file")
	}
}

func TestGenerateIsDeterministic(t *testing.T) {
	dir := t.TempDir()
	feature := Feature{
		Name: "F",
		Scenarios: []Scenario{{
			Name:     "ordered",
			Steps:    []Step{{Keyword: "Then", Text: "ok"}},
			Examples: []map[string]string{{"a": "1"}},
		}},
	}
	ir := writeFeatureIR(t, dir, feature)
	gen := func(out string) string {
		files, err := Generate(GenerateOptions{IRPath: ir, OutputDir: out, FeaturePath: "features/f.feature"})
		if err != nil {
			t.Fatal(err)
		}
		body, _ := os.ReadFile(files[0])
		return string(body)
	}
	a := gen(filepath.Join(dir, "out1"))
	b := gen(filepath.Join(dir, "out2"))
	if a != b {
		t.Error("generation is not deterministic")
	}
}

func TestGenerateLoadFailure(t *testing.T) {
	if _, err := Generate(GenerateOptions{IRPath: filepath.Join(t.TempDir(), "missing.json"), OutputDir: t.TempDir()}); err == nil {
		t.Fatal("expected error for missing IR")
	}
}
