package apskit

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var safeIdent = regexp.MustCompile(`[^A-Za-z0-9_]+`)

// SafeIdentifier converts arbitrary text into a Go-safe identifier fragment.
func SafeIdentifier(text string) string {
	cleaned := safeIdent.ReplaceAllString(text, "_")
	cleaned = strings.Trim(cleaned, "_")
	if cleaned == "" {
		return "Scenario"
	}
	return cleaned
}

// GenerateOptions configures Generate.
type GenerateOptions struct {
	IRPath      string
	OutputDir   string
	FeaturePath string // defaults to IRPath
	PackageName string // defaults to "generated"
}

// Generate writes a Go test file plus metadata for one feature. Returns the
// list of generated files contributing to the implementation hash.
func Generate(opts GenerateOptions) ([]string, error) {
	feature, err := LoadIR(opts.IRPath)
	if err != nil {
		return nil, err
	}
	if opts.FeaturePath == "" {
		opts.FeaturePath = opts.IRPath
	}
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "generated"
	}
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return nil, err
	}
	stem := strings.TrimSuffix(filepath.Base(opts.FeaturePath), filepath.Ext(opts.FeaturePath))
	testFile := filepath.Join(opts.OutputDir, strings.ToLower(SafeIdentifier(stem))+"_acceptance_test.go")

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by acceptance-entrypoint-generator. Do not edit.\n")
	fmt.Fprintf(&b, "// Feature: %s\n", feature.Name)
	fmt.Fprintf(&b, "// Source: %s\n", opts.FeaturePath)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"os\"\n")
	fmt.Fprintf(&b, "\t\"testing\"\n\n")
	fmt.Fprintf(&b, "\t\"github.com/vadimcomanescu/acceptance-pipeline-kit/go/apskit\"\n")
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "func irPath() string {\n")
	fmt.Fprintf(&b, "\tif p := os.Getenv(\"APS_IR_PATH\"); p != \"\" {\n\t\treturn p\n\t}\n")
	fmt.Fprintf(&b, "\treturn %q\n", opts.IRPath)
	fmt.Fprintf(&b, "}\n\n")

	for _, pair := range ExecutionsFor(feature) {
		sIdx, eIdx := pair[0], pair[1]
		scenarioName := SafeIdentifier(feature.Scenarios[sIdx].Name)
		fnName := fmt.Sprintf("Test_Scenario_%02d_%s_Example_%02d", sIdx, scenarioName, eIdx+1)
		fmt.Fprintf(&b, "func %s(t *testing.T) {\n", fnName)
		fmt.Fprintf(&b, "\tif err := apskit.RunExecution(irPath(), %d, %d, nil); err != nil {\n", sIdx, eIdx)
		fmt.Fprintf(&b, "\t\tt.Fatal(err)\n\t}\n")
		fmt.Fprintf(&b, "}\n\n")
	}

	if err := os.WriteFile(testFile, []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	generated := []string{testFile}
	if _, err := WriteMetadata(MetadataInput{
		MetadataDir:    filepath.Join(opts.OutputDir, "metadata"),
		FeaturePath:    opts.FeaturePath,
		IRPath:         opts.IRPath,
		GeneratedFiles: generated,
	}); err != nil {
		return nil, err
	}
	return generated, nil
}

// mutate4go-manifest-begin
// {"version":1,"tested_at":"2026-05-28T18:17:14+02:00","module_hash":"73837e8cfc8da6c745491c32091f33d8a53144926249d6a13fd2d8cd46d7b6ae","functions":[{"id":"func/SafeIdentifier","name":"SafeIdentifier","line":14,"end_line":21,"hash":"5aa7e33693affedcaf1b890dbe43426f048cf23e1d5160fb15fb1d7a942cd48b"},{"id":"func/Generate","name":"Generate","line":33,"end_line":90,"hash":"82d310f84b6140a48faaf9ec8eaed25b128450d77e99db4fc6162d88b162768d"}]}
// mutate4go-manifest-end
