import json
from pathlib import Path

from aps_kit.generator import generate


def _write_ir(tmp_path: Path, ir: dict) -> Path:
    p = tmp_path / "ir.json"
    p.write_text(json.dumps(ir), encoding="utf-8")
    return p


def test_emits_one_test_per_execution(tmp_path: Path) -> None:
    ir = {
        "name": "Calculator",
        "background": [{"keyword": "Given", "text": "a fresh calculator"}],
        "scenarios": [
            {
                "name": "addition",
                "steps": [{"keyword": "Then", "text": "ok"}],
                "examples": [{"a": "1"}, {"a": "2"}],
            },
            {
                "name": "no examples",
                "steps": [{"keyword": "Then", "text": "ok"}],
                "examples": [],
            },
        ],
    }
    ir_path = _write_ir(tmp_path, ir)
    out = tmp_path / "out"
    generated = generate(ir_path, out, feature_path="features/calc.feature")
    assert len(generated) == 1
    body = generated[0].read_text()
    assert "Generated by acceptance-entrypoint-generator" in body
    assert body.count("def test_scenario_") == 3
    meta = json.loads((out / "metadata" / "features-calc-feature.json").read_text())
    assert meta["schema_version"] == 1
    assert meta["hash_scope"] == "generated_files"
    assert meta["implementation_hash"].startswith("sha256:")


def test_default_feature_path_falls_back_to_ir_path(tmp_path: Path) -> None:
    ir_path = _write_ir(
        tmp_path,
        {"name": "F", "scenarios": [{"name": "s", "steps": [{"keyword": "Then", "text": "ok"}], "examples": []}]},
    )
    out = tmp_path / "out"
    generate(ir_path, out)
    # Filename derives from the IR path when no feature_path is given.
    files = list((out / "metadata").iterdir())
    assert len(files) == 1
    assert files[0].suffix == ".json"


def test_unnamed_scenario_falls_back_to_default_identifier(tmp_path: Path) -> None:
    ir_path = _write_ir(
        tmp_path,
        {
            "name": "F",
            "scenarios": [{"name": "@@@", "steps": [{"keyword": "Then", "text": "ok"}], "examples": []}],
        },
    )
    out = tmp_path / "out"
    generated = generate(ir_path, out, feature_path="features/f.feature")
    body = generated[0].read_text()
    # The all-punctuation scenario name collapses to a stable identifier.
    assert "def test_scenario_00_scenario_example_01" in body


def test_generation_is_deterministic(tmp_path: Path) -> None:
    ir_path = _write_ir(
        tmp_path,
        {
            "name": "F",
            "scenarios": [
                {
                    "name": "ordered",
                    "steps": [{"keyword": "Then", "text": "ok"}],
                    "examples": [{"a": "1"}],
                }
            ],
        },
    )
    out1 = tmp_path / "out1"
    out2 = tmp_path / "out2"
    g1 = generate(ir_path, out1, feature_path="features/f.feature")[0].read_text()
    g2 = generate(ir_path, out2, feature_path="features/f.feature")[0].read_text()
    assert g1 == g2
