"""Acceptance entrypoint generator. Emits a pytest module for a single feature."""
from __future__ import annotations

import re
from pathlib import Path
from textwrap import dedent

from .ir import load_ir
from .metadata import write_metadata
from .runtime import executions_for

_SAFE_NAME = re.compile(r"[^A-Za-z0-9_]+")


def _safe_identifier(text: str) -> str:
    cleaned = _SAFE_NAME.sub("_", text).strip("_").lower()
    return cleaned or "scenario"


def _module_stem(feature_path: str) -> str:
    stem = Path(feature_path).stem
    return f"{_safe_identifier(stem)}_acceptance_test"


def generate(
    ir_path: Path,
    output_dir: Path,
    *,
    feature_path: str | None = None,
) -> list[Path]:
    """Generate the pytest entry-point module and metadata for one feature.

    Returns the list of generated file paths (test files first, metadata files
    are tracked separately and not part of the implementation hash).
    """
    feature = load_ir(ir_path)
    fp = feature_path or str(ir_path)
    module_stem = _module_stem(fp)
    output_dir.mkdir(parents=True, exist_ok=True)
    test_file = output_dir / f"{module_stem}.py"

    lines: list[str] = []
    lines.append("# Generated by aps-generate. Do not edit.")
    lines.append(f"# Feature: {feature.name}")
    lines.append(f"# Source: {fp}")
    lines.append("import os")
    lines.append("from aps_kit.runtime import run_execution")
    lines.append("")
    lines.append(
        f'_IR_PATH = os.environ.get("APS_IR_PATH", {str(ir_path)!r})'
    )
    lines.append("")
    for s_idx, e_idx in executions_for(feature):
        scenario_name = _safe_identifier(feature.scenarios[s_idx].name)
        fn_name = f"test_scenario_{s_idx:02d}_{scenario_name}_example_{e_idx + 1:02d}"
        lines.append(
            f"def {fn_name}() -> None:\n"
            f"    run_execution(_IR_PATH, {s_idx}, {e_idx})\n"
        )

    test_file.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    # Per APS metadata rules: implementation hash covers generated files only.
    generated_files = [test_file]
    metadata_dir = output_dir / "metadata"
    write_metadata(
        metadata_dir,
        feature_path=fp,
        ir_path=str(ir_path),
        generated_files=generated_files,
    )
    return generated_files
