use std::fs;
use std::path::{Path, PathBuf};

use aps_kit::generator::{generate, GenerateOptions};

fn write_ir(path: &Path, contents: &str) {
    fs::write(path, contents).unwrap();
}

#[test]
fn emits_one_test_per_execution_with_canonical_comment() {
    let tmp = tempdir();
    let ir = tmp.path().join("ir.json");
    write_ir(
        &ir,
        r#"{
            "name": "F",
            "scenarios": [
                {"name": "with examples", "steps": [{"keyword":"Then","text":"ok"}], "examples":[{"a":"1"},{"a":"2"}]},
                {"name": "no examples", "steps": [{"keyword":"Then","text":"ok"}], "examples":[]}
            ]
        }"#,
    );
    let out = tmp.path().join("out");
    let generated = generate(GenerateOptions {
        ir_path: &ir,
        output_dir: &out,
        feature_path: Some("features/foo.feature"),
        handlers_crate: "handlers",
    })
    .unwrap();
    assert_eq!(generated.len(), 1);
    let body = fs::read_to_string(&generated[0]).unwrap();
    assert!(body.contains("Generated by acceptance-entrypoint-generator"));
    assert_eq!(body.matches("#[test]\nfn scenario_").count(), 3);
    let meta = fs::read_to_string(out.join("metadata").join("features-foo-feature.json")).unwrap();
    assert!(meta.contains("\"schema_version\": 1"));
}

#[test]
fn falls_back_to_ir_path_when_feature_path_unspecified() {
    let tmp = tempdir();
    let ir = tmp.path().join("ir.json");
    write_ir(
        &ir,
        r#"{"name":"F","scenarios":[{"name":"s","steps":[],"examples":[]}]}"#,
    );
    let out = tmp.path().join("out");
    generate(GenerateOptions {
        ir_path: &ir,
        output_dir: &out,
        feature_path: None,
        handlers_crate: "handlers",
    })
    .unwrap();
    let metadata_dir = out.join("metadata");
    let entries: Vec<_> = fs::read_dir(&metadata_dir).unwrap().collect();
    assert_eq!(entries.len(), 1);
}

#[test]
fn unnamed_scenario_falls_back_to_default_identifier() {
    let tmp = tempdir();
    let ir = tmp.path().join("ir.json");
    write_ir(
        &ir,
        r#"{"name":"F","scenarios":[{"name":"@@@","steps":[{"keyword":"Then","text":"ok"}],"examples":[]}]}"#,
    );
    let out = tmp.path().join("out");
    let files = generate(GenerateOptions {
        ir_path: &ir,
        output_dir: &out,
        feature_path: Some("features/f.feature"),
        handlers_crate: "handlers",
    })
    .unwrap();
    let body = fs::read_to_string(&files[0]).unwrap();
    assert!(body.contains("fn scenario_00_scenario_example_01"));
}

#[test]
fn deterministic_for_a_fixed_ir() {
    let tmp = tempdir();
    let ir = tmp.path().join("ir.json");
    write_ir(
        &ir,
        r#"{"name":"F","scenarios":[{"name":"ordered","steps":[{"keyword":"Then","text":"ok"}],"examples":[{"a":"1"}]}]}"#,
    );
    let gen = |out: PathBuf| -> String {
        let files = generate(GenerateOptions {
            ir_path: &ir,
            output_dir: &out,
            feature_path: Some("features/f.feature"),
            handlers_crate: "handlers",
        })
        .unwrap();
        fs::read_to_string(&files[0]).unwrap()
    };
    assert_eq!(gen(tmp.path().join("a")), gen(tmp.path().join("b")));
}

#[test]
fn load_failure_propagates() {
    let tmp = tempdir();
    let result = generate(GenerateOptions {
        ir_path: &tmp.path().join("missing.json"),
        output_dir: &tmp.path().join("out"),
        feature_path: None,
        handlers_crate: "handlers",
    });
    assert!(result.is_err());
}

struct TempDir(std::path::PathBuf);
impl TempDir {
    fn path(&self) -> &std::path::Path { &self.0 }
}
impl Drop for TempDir {
    fn drop(&mut self) { let _ = std::fs::remove_dir_all(&self.0); }
}
fn tempdir() -> TempDir {
    let mut p = std::env::temp_dir();
    p.push(format!(
        "aps-kit-test-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&p).unwrap();
    TempDir(p)
}
